***REMOVED*** Grafana Datasource Provisioning
***REMOVED*** Automatically configures Loki, Tempo, and Mimir datasources

apiVersion: 1

datasources:
  ***REMOVED*** Loki - Logs datasource
  - name: Loki
    type: loki
    access: proxy
    uid: LOKI
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        ***REMOVED*** Extract trace ID from logs and link to Tempo
        - datasourceUid: TEMPO
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    orgId: 1

  ***REMOVED*** Tempo - Traces datasource
  - name: Tempo
    type: tempo
    access: proxy
    uid: TEMPO
    url: http://tempo:3200
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        ***REMOVED*** Link traces to logs in Loki
        datasourceUid: LOKI
        tags: [ 'service.name', 'deployment.environment' ]
        mappedTags: [ { key: 'service.name', value: 'service' } ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        ***REMOVED*** Link traces to metrics in Mimir
        datasourceUid: MIMIR
        tags: [ { key: 'service.name', value: 'service' } ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: MIMIR
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: LOKI
    orgId: 1

  ***REMOVED*** Mimir - Metrics datasource (Prometheus-compatible)
  - name: Mimir
    type: prometheus
    access: proxy
    uid: MIMIR
    url: http://mimir:9009/prometheus
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        ***REMOVED*** Link exemplars to traces in Tempo
        - name: traceID
          datasourceUid: TEMPO
    orgId: 1